TaskOne/Models/Assignments.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TaskOne.Models
{
    public class Assignments
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Assignment Name")]
        public string AssignmentTitle { get; set; }

        [NotMapped]
        [FileValidation(new string[] { ".jpg", ".jpeg", ".png", ".gif",".pdf" }, 5 * 1024 * 1024, ErrorMessage = "Invalid file.")]
        [Required]
        public List<IFormFile>? Files { get; set; }
    }
}

TaskOne/Models/ErrorViewModel.cs
namespace TaskOne.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TaskOne/Models/FilePath.cs
namespace TaskOne.Models
{
    public class FilePath
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public int AssignmentId { get; set; }
        public Assignments Assignment { get; set; }
    }
}

TaskOne/Models/FileValidationAttribute .cs
using System.ComponentModel.DataAnnotations;

namespace TaskOne.Models
{
    public class FileValidationAttribute : ValidationAttribute
    {
        private readonly string[] AllowedExtensions;
        private readonly long MaxSizeInBytes;

        public FileValidationAttribute(string[] allowedExtensions, long maxSizeInBytes)
        {
            AllowedExtensions = allowedExtensions;
            MaxSizeInBytes = maxSizeInBytes;
        }

        protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
        {
            if (value is List<IFormFile> files)
            {
                if (files.Count > 5)
                {
                    return new ValidationResult($"Maximum 5 Files are Allowed to Attach.");
                }
                foreach (var file in files)
                {

                    if (file.Length > MaxSizeInBytes)
                    {
                        return new ValidationResult($"File size exceeds the maximum allowed size of {MaxSizeInBytes / 1024} KB.");
                    }

                    var fileExtension = Path.GetExtension(file.FileName);
                    if (!AllowedExtensions.Contains(fileExtension.ToLower()))
                    {
                        return new ValidationResult($"Only {string.Join(", ", AllowedExtensions)} files are allowed.");
                    }
                }
            }
            return ValidationResult.Success;
        }
    }
}

TaskOne/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Xml.XPath;
using TaskOne.Models;
using TaskOne.Repository;

namespace TaskOne.Controllers
{
    public class AssignmentController : Controller
    {
        private readonly IAssignmentRepository assignmentRepo;
        private readonly IWebHostEnvironment Env;

        public AssignmentController(IAssignmentRepository _assignmentRepo, IWebHostEnvironment env)
        {
            assignmentRepo = _assignmentRepo;
            Env = env;
        }

        public IActionResult Index()
        {
            var assignments = assignmentRepo.GetAllAssignments();
            return View(assignments);
        }
        [HttpGet]
        public IActionResult UploadAssignment()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UploadAssignment(Assignments assignment)
        {
            if (ModelState.IsValid)
            {
                if (assignment != null)
                {
                    if (assignment.Files != null && assignment.Files.Count > 0)
                    {
                        var pathitems = new List<FilePath>();
                        var assignmentitems = new List<Assignments>();
                        foreach (var file in assignment.Files)
                        {
                            if (file.Length > 0)
                            {
                                // Saving to Folder and KeepRecord in Database
                                var GuidId = Guid.NewGuid();
                                var JMMFilePath = Path.Combine(Env.WebRootPath, "img", GuidId + Path.GetExtension(file.FileName));
                                var pathtoSaveinDB = Path.Combine("\\" + "img", GuidId + Path.GetExtension(file.FileName));
                                using (var stream = new FileStream(JMMFilePath, FileMode.Create))
                                {
                                    file.CopyTo(stream);
                                }

                                // Store the file path in the list
                                assignmentitems.Add(new Assignments { AssignmentTitle = assignment.AssignmentTitle });
                                pathitems.Add(new FilePath { Path = pathtoSaveinDB, AssignmentId = assignment.Id });
                            }
                        }
                        //Save in Db
                        var SavedAssignment = assignmentRepo.CreateAssignment(assignment);
                        foreach (var filePath in pathitems)
                        {
                            filePath.AssignmentId = SavedAssignment.Id;
                        }
                        //Save Assignment Files Paths
                        assignmentRepo.SaveFilePaths(pathitems);
                        ViewBag.ResultMessage = "Files Added Successfully";
                        ModelState.Clear();
                        return View();
                    }
                }
            }
            return View(assignment);
        }
        public IActionResult GetFiles(int id)
        {
            var filepaths = assignmentRepo.GetFilesbyAssignmentId(id);
            if (filepaths.Count() > 0)
            {
                return View(filepaths);
            }
            return View();
        }
        [HttpGet]
        public IActionResult DownloadFile(string FilePath)
        {
            string GetFileName = Path.GetFileName(FilePath);

            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", GetFileName);
            var mimeType = "application/octet-stream";

            return File(System.IO.File.OpenRead(filePath), mimeType, GetFileName);
        }
    }
}

TaskOne/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TaskOne.Models;

namespace TaskOne.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TaskOne/Views/Assignment/GetFiles.cshtml
@model IEnumerable<TaskOne.Models.FilePath>

<br />
<br />
<div class="border p-4 bg-white">
    <div class="row">
        <div class="col-8">
            <h2 class="text-info"> Assignment File List</h2>
        </div>
    </div>
    <br />
    <div>
        @if (Model != null)
        {
            @if (Model.Count() > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            Assignment Id
                        </th>
                        <th>Assignment Id</th>
                        <th>View File</th>
                        <th>Download File</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.AssignmentId
                            </td>
                           <td>
                                @item.Assignment.AssignmentTitle
                           </td>
                           <td>
                                @{
                                    string fullUrl = item.Path;
                                    string[] urlParts = fullUrl.Split(new[] { "\\img\\" }, StringSplitOptions.None);
                                    string fileName = urlParts.Length > 1 ? urlParts[1] : "";
                                }
                                <a href="@item.Path" target="_blank">View File</a>
                           </td> 
                           <td>
                                <a href="@Url.Action("DownloadFile", "Assignment", new { FilePath = item.Path })">Download File</a>
                           </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>No file links exists...</p>
            }
        }
        else
        {
            <p>No file links exists...</p>
        }
    </div>
</div>

TaskOne/Views/Assignment/Index.cshtml
@model IEnumerable<TaskOne.Models.Assignments>

<br />
<br />
<div class="border p-4 bg-white">
    <div class="row">
        <div class="col-8">
            <h2 class="text-info"> Assignment List</h2>
        </div>
        <div class="col-2 text-right">
            <a asp-action="UploadAssignment" class="btn btn-info form-control"> Create New Assignment </a>
        </div>
    </div>
    <br />
    <div>
        @if (Model.Count() > 0)
        {
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        Assignment Id
                    </th>
                    <th>Assingment Name</th>
                    <th>
                        Assignment Files
                    </th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Id
                        </td>
                        <td>@item.AssignmentTitle</td>
                        <td>
                            <a class="btn btn-primary text-white" asp-action="GetFiles" asp-route-Id="@item.Id">
                            View Files
                        </a>
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>No publisher exists...</p>
        }
    </div>
</div>

TaskOne/Views/Assignment/UploadAssignment.cshtml
@model TaskOne.Models.Assignments

@if (ViewBag.ResultMessage != null)
{
    <div class="alert alert-success">@ViewBag.ResultMessage</div>
}
<form method="post" enctype="multipart/form-data" asp-action="UploadAssignment" asp-controller="Assignment">
    <div class="form-group">
        <label asp-for="AssignmentTitle"></label>
        <input asp-for="AssignmentTitle" class="form-control" />
        <span asp-validation-for="AssignmentTitle" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Files"></label>
        <input asp-for="Files" type="file" multiple class="form-control" />
        <span asp-validation-for="Files" class="text-danger"></span>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

TaskOne/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TaskOne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskOne</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskOne.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskOne</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assignment" asp-action="Index">Assignments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TaskOne - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>